### ISSUE TITLE
Öde butonu yok!

### ISSUE THREAD

**Issue by FlySquare** [mewebstudio/paytr#1]
Selam. kaynak kod için çok teşekkür ederim ancak ödeme sayfasında (payment.php) hiçbir şekilde ödeme butonu aktif olmuyor. bunun sebebi nedir acaba? test form verileri vs geliyor ancak öde butonu yok bir çok yol denedim ama getiremedim yardım eder misin?

**Comment by harpiya** [comment]
payment.php dosyasını iframe kodunu aşağıdaki şekilde değiştirirsen sorun çözülür. Iframe'de scroll kapalı olduğu için görüntülenmiyor.

`<div class="container">
    <script src="https://www.paytr.com/js/iframeResizer.min.js"></script>
<iframe src="https://www.paytr.com/odeme/guvenli/<?php echo $payment->getResponse()->getToken(); ?>" id="paytriframe" frameborder="0" scrolling="no" style="width: 100%;"></iframe>
<script>iFrameResize({},'#paytriframe');</script>
</div>`

**Comment by FlySquare** [comment]
tekrar selam. verdiğin kod sayesinde ödeme alabiliyorum ancak ödemeyi paytr ye bildiremiyorum. buunn için içerisinde gömülü kod var mı kullanmam için yada tavsiye verir misin. şuan test ortamında çalışıyorum
