### ISSUE TITLE
Yardım

### ISSUE THREAD

**Issue by mebularts** [mewebstudio/paytr#12]
Henüz Başlangıç düzeyinde bir .PHP biliyorum ve ne yaptıysam siteme PayTR'yi ekleyemedim baktığımda detaylı bir video da yok açıkçası ve kullandığım scriptte biraz karışık bu konuda bana yardımcı olabilecek var mı?
Site'de PayPal ve Stripe gibi ödeme seçenekleri var başta paypal yerine kodları paytr ile değiştirerek yapmak istedim fakat olmuyor her ne yaptıysam o kısımda gösteremedim

**Comment by mewebstudio** [comment]
Merhaba,

Olay örgüsü için examples dizinini incelemeniz gerekiyor. README.md dosyasında en alt satırlarda bundan bahsedildi.
examples dizininde; index.php ile sipariş formu gönderildikten sonra, payment.php’de sipariş oluşturulup PayTR’ye gönderiliyor ve PayTR’nin sunduğu form render edilerek, kredi kartı ile kullanıcıdan ödeme alınması sağlanıyor. Ödeme alındıktan sonra callback.php’ye PayTR bir istek gönderiyor ve ödemenin olumlu/olumsuz sonuçlandığına dair bize bilgi veriyor. Süreç bundan ibarettir.

İyi çalışmalar.
