### ISSUE TITLE
İframe Problemi

### ISSUE THREAD

**Issue by Mrjavaci** [mewebstudio/paytr#13]
Yazdığınız paketi AIMEOS üzerinde extension hâline getirmeye çalışıyorum. 

Aşağıda göreceğiniz üzre token alma işlemim başarıyla gerçekleşiyor ve token dönüyor. 

![Ekran Resmi 2023-03-26 02 19 25](https://user-images.githubusercontent.com/37361318/227746948-fec06254-5d24-4b3a-8434-94d48f61d4a9.png)

Ancak, aşağıdaki problemle karşılaşıyorum. Cors'tan dolayı yaptığını düşünmekteyim ancak local development serverim vhost'tan domain ile çıkmakta. Zaten iframe için cors ayarları paytr'de aktif olsa, kimse kullanamazdı. 

![Ekran Resmi 2023-03-26 02 19 50](https://user-images.githubusercontent.com/37361318/227746963-aaabbbf4-6a86-4a13-aaa1-6ab11d4f9762.png)

Sizce neden böyle bir problem ile karşılaştım, fikriniz nelerdir?

Not: İframe linkine gittiğimde doğru sayfaya ulaşmaktayım, bilginize.

**Comment by mewebstudio** [comment]
Merhaba, açıkçası hiçbir fiktim yok.. Browser kaynaklı olabilir, farklı bir browser ile denediniz mi?
