### ISSUE TITLE
Payment Sınıfı merchant_ok_url, merchant_fail_url, timeout_limit aynı değere sahip

### ISSUE THREAD

**Issue by eminakcil** [mewebstudio/paytr#3]
İncelerken fark ettim Payment sınıfı prepare fonksiyonunda aşağıdaki üç anahtar aynı değere eşleştirilmiş
`'merchant_ok_url' => $this->config->getSuccessUrl(),`
`'merchant_fail_url' => $this->config->getSuccessUrl(),`
`'timeout_limit' => $this->config->getSuccessUrl(),`

**Comment by mewebstudio** [comment]
https://github.com/mewebstudio/paytr/pull/4
