### ISSUE TITLE
vendor/autoload.php

### ISSUE THREAD

**Issue by muratozerce** [mewebstudio/paytr#5]
example/payment.php dosyasında `require __DIR__ . '/../vendor/autoload.php';` kodu var ancak böyle bir dosya yok. Bu yüzden ödeme sayfasında form doldurulduktan sonra hata alıyorum. Bu dosyayı nereden temin edeibilirim?

**Comment by ozilion** [comment]
Composer install işlemi sonrasında autoload dosyası vendor klasörü içerisinde otomatik olarak oluşturulur.

**Comment by mewebstudio** [comment]
`composer install` komutu işletmeniz gerekiyor.
